import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Kamrul Islam Apurba",
  description: "Generated by Kamrul Islam Apurba",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Navbar />


        <main className="min-h-screen">
          {children}
        </main>


        <footer className="bg-gray-950 text-white py-6 text-center">
          <div className="container mx-auto px-4">
            <p className="text-sm">&copy; {new Date().getFullYear()} Kamrul Islam Apurba. All rights reserved.</p>
            <div className="flex justify-center space-x-4 mt-2">
              <a href="#" className="hover:text-gray-400 transition">Privacy Policy</a>
              <span>|</span>
              <a href="#" className="hover:text-gray-400 transition">Terms of Service</a>
            </div>
          </div>
        </footer>

      </body>
    </html>
  );
}
